# Generated by Django 5.2.4 on 2025-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
