# Generated by Django 5.2.7 on 2025-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_alter_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
