# Generated by Django 5.2.7 on 2025-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='dummy', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.CharField(default='dummy', max_length=100),
        ),
    ]
