# Generated by Django 5.2.7 on 2025-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_book_category_book_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fine_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Fine per day in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='borrow',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
