# Generated by Django 5.2.7 on 2025-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_book_fine_rate_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
