# Generated by Django 5.2.7 on 2025-10-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_admin_department_admin_designation_admin_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='full_name',
        ),
    ]
