# Generated by Django 5.2.7 on 2025-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_remove_admin_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='fine_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Fine per day in rupees (₹)', max_digits=10),
        ),
    ]
