# Generated by Django 5.2.7 on 2025-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_borrow_reject_reason_alter_book_fine_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or disabling', null=True),
        ),
    ]
