# Generated by Django 5.2.10 on 2026-04-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_post_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('borrow_confirmed', 'Borrow Confirmed'), ('reminder_7day', '7-Day Return Reminder'), ('reminder_2day', '2-Day Return Reminder'), ('reminder_1day', '1-Day Return Reminder'), ('overdue_admin', 'Overdue Alert to Admin'), ('fine_daily', 'Daily Fine Notification'), ('fine_waived', 'Fine Waived Notification')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('borrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lms_app.borrow')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FineWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waived_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_approvals', to='lms_app.admin')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='lms_app.borrow')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_requests', to='lms_app.admin')),
            ],
        ),
    ]
