# Generated by Django 5.2.10 on 2026-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_emailnotificationlog_finewaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('borrow_confirmed', 'Borrow Confirmed'), ('reminder_7day', '7-Day Return Reminder'), ('reminder_2day', '2-Day Return Reminder'), ('reminder_1day', '1-Day Return Reminder'), ('overdue_admin', 'Overdue Alert to Admin'), ('fine_daily', 'Daily Fine Notification'), ('fine_waived', 'Fine Waived Notification'), ('signup_received', 'Signup Request Received'), ('signup_approved', 'Signup Approved')], max_length=30),
        ),
    ]
