# Generated by Django 5.2.4 on 2025-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowlog',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
